# Generated by Django 4.2.7 on 2023-11-23 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=225, unique=True)),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='client/profile_pic/')),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('stripe_client_id', models.CharField(blank=True, max_length=225)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=225)),
                ('stripe_card_last_octet', models.CharField(blank=True, max_length=225)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=300)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=25)),
                ('amount', models.IntegerField(default=1)),
                ('picture', models.ImageField(upload_to='Request/pictures')),
                ('status', models.CharField(choices=[('Creating', 'Creating'), ('Processing', 'Processing'), ('Picking', 'Picking'), ('Delivering', 'Delivering'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Creating', max_length=25)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FlashDS.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlashDS.client')),
            ],
        ),
    ]
