# Generated by Django 4.2.7 on 2023-11-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashDS', '0003_request_pickup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
