# Generated by Django 4.2.7 on 2023-11-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashDS', '0004_request_delivery_address_request_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
