# Generated by Django 4.2.7 on 2023-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashDS', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivered_Time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/delivery_pic/'),
        ),
        migrations.AddField(
            model_name='request',
            name='pickup_Time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='pickup_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/pickup_pic/'),
        ),
    ]
