# Generated by Django 4.2.7 on 2023-11-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlashDS', '0008_courier_request_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlashDS.courier'),
        ),
    ]
