# Generated by Django 4.2.7 on 2023-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashDS', '0009_alter_request_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='paypal_mail',
            field=models.EmailField(blank=True, max_length=225),
        ),
    ]
