# Generated by Django 4.2.7 on 2023-12-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashDS', '0010_courier_paypal_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('earn', 'earn'), ('refund', 'refund')], default='earn', max_length=25),
        ),
    ]
