# Generated by Django 4.2.7 on 2023-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashDS', '0011_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('earned', 'earned'), ('refund', 'refund')], default='earned', max_length=25),
        ),
    ]
